version: 2.1
orbs:
  r-packages: displayr/r-packages@dev:7150d968a0f747b4a123ee90bd1fff22fe553f00
parameters:
  trigger-message:
    type: string
    default: ""
  remote-deps:
    type: string
    default: ""
  plugins-branch:
    type: string
    default: ""
  triggered-packages:
    type: string
    default: ""
  executor:
    type: enum
    enum: [nightly, rocker, machine, rocker_geo]
    default: rocker

workflows:
  build-and-check-R-package:
    jobs:
      - r-packages/build_and_check_package:
          executor: << pipeline.parameters.executor >>
          name: BuildAndCheckPackage
          context:
            - r_packages
          remote_deps: << pipeline.parameters.remote-deps >>
          separate_test_job: false
      - r-packages/deploy_package:
          executor: << pipeline.parameters.executor >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          filters:
            branches:
              only:
                - master
      - r-packages/trigger_revdeps:
          executor: << pipeline.parameters.executor >>
          requires:
            - BuildAndCheckPackage
          context:
            - r_packages
          remote_deps: << pipeline.parameters.remote-deps >>
          plugins_branch: << pipeline.parameters.plugins-branch >>
          trigger_message: << pipeline.parameters.trigger-message >>
          triggered_packages: << pipeline.parameters.triggered-packages >>
