name: Build flipStartup

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build flipStartup
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.flipStartup
      build-args: --override-input flipStartup .
      installable-name: flipStartup
    secrets: inherit
